# Generated by Django 6.0.4 on 2026-04-28 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(db_column='department', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(db_column='academic_level', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='matric_no',
            field=models.CharField(db_column='matriculation_number', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
    ]
