# Generated by Django 6.0.4 on 2026-04-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('quiz', 'Quiz'), ('assignment', 'Assignment'), ('exam', 'Exam'), ('mid_semester', 'Mid Semester')], max_length=20)),
                ('score', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
    ]
