# Generated by Django 6.0.4 on 2026-04-28 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_initial'),
        ('students', '0003_alter_student_department_alter_student_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='date',
            field=models.DateField(db_column='assessment_date'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='score',
            field=models.FloatField(db_column='score'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='student',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='type',
            field=models.CharField(choices=[('quiz', 'Quiz'), ('assignment', 'Assignment'), ('exam', 'Exam'), ('mid_semester', 'Mid Semester')], db_column='assessment_type', max_length=20),
        ),
        migrations.AlterModelTable(
            name='assessment',
            table='assessment',
        ),
    ]
