# Generated by Django 6.0.4 on 2026-05-01 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_alter_assessment_date_alter_assessment_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='subject',
            field=models.CharField(db_column='subject', default=1, max_length=100),
            preserve_default=False,
        ),
    ]
