# Generated by Django 6.0.4 on 2026-04-28 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0002_initial'),
        ('students', '0003_alter_student_department_alter_student_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='date',
            field=models.DateField(db_column='performance_date'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='gpa',
            field=models.FloatField(db_column='gpa'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='remarks',
            field=models.TextField(db_column='remarks'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='student',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AlterModelTable(
            name='performance',
            table='performance',
        ),
    ]
