# Generated by Django 6.0.4 on 2026-05-01 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0003_alter_performance_date_alter_performance_gpa_and_more'),
        ('students', '0004_student_created_at_student_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='date',
        ),
        migrations.AddField(
            model_name='performance',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='performance',
            name='gpa',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='performance',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='performance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='students.student'),
        ),
    ]
